### ISSUE TITLE
Friday 15 March Checklist

### ISSUE THREAD

**Issue by stuartleech** [cookiewolf/bi4c8d#142]
## Katja
- [x] Add Title to top of page 
- [x] Change width of message boxes to 480px including avatar
- [x] Change text size to 20px for main text
- [x] Main text boxes narrower
- [x] Section 2 black background - black backgrounds should go full width of screen
- [x] #158
- [ ] #155
- [x] Section 4 Image recognition images make 50% opacity apart from final black image
- [x] Section 7 Make background black
- [x] #157
- [x] Fix lock-bit width
- [x] max-width 800
- [x] Center justify content of portraits
- [x] 1st image full opacity in stacking
- [ ] #163

## Stuart
- [x] Section 2 Add more images - SL
- [x] Replace covid graph with crime graph from Figma
- [ ] #165
- [x] Stuart Add text block for Section 6
- [x] Get videos for messages
- [x] Hackney data loss interview populate
- [ ] #166
- [x] Spread out icons and make slight larger `/images/main-text-icons.svg`

**Comment by stuartleech** [comment]
@katjam I've added a main text block to section 6 but it's not appearing so might be missing?

**Comment by katjam** [comment]
> @katjam I've added a main text block to section 6 but it's not appearing so might be missing?

I think it's there in the code. If you are doing it local, you need to `npm run generate` to update from CMS

**Comment by stuartleech** [comment]
I'm going to add some info about the graphs here: 

1. Trust in Government Graph 

<img width="547" alt="Screenshot 2024-03-15 at 17 25 39" src="https://github.com/cookiewolf/bi4c8d/assets/15141003/66f1314a-fe00-4377-8d38-9bdb30f13267">


2. Public Order and Safety Spending 1999 - 2023

Public Order and Safety spending, 1999-2023 Graph:
1999/20 – 2022/23
31.1 	
34.1 	
37.8 	
39.1 	
41.3 	
43.3 	
43.3 	
43.6 	
44.4 	
45.6 	
45.5 	
43.4 	
41.4 	
39.7 	
36.8 	
37.1 	
36.8 	
35.9 	
37.0 	
37.4 	
38.8 	
41.2 	
42.4 	
43.9

**Comment by stuartleech** [comment]
Can we use Vimeo? https://vimeo.com/923841832?share=copy

This is the video but it doesn't have sound so just need to check with Christo

**Comment by katjam** [comment]
closing as re-ticketted
