### ISSUE TITLE
Terminal

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#174]
- [ ] Add font
- [x] basic styles
- [x] Welcome text
- [x] Prompt with input
- [x] Add to CMS - command, helpText, content
- [ ] Help command by default
 
## Terminal state
- [ ] Command history
- [ ] Output generated from command history.
- [ ] Current input
