### ISSUE TITLE
Pile of draggable content

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#209]
https://apossible.com

## Messages
Section 1, 7, 11

## Images
Section 2, (new) 5.5 - before hmrc terminal

## Acceptance criteria

- [ ] elements can be clicked and moved around
- [ ] clicked element comes to front of pile
- [ ] constrain elements movement within container
- [ ] at smaller screen sizes revert to a static list view

## Implementation plan

- https://package.elm-lang.org/packages/zaboco/elm-draggable/latest/ looks like the tool for the job
- will start by trying to implement a version of their multiple target example using html instead of svg and accepts a list of html children as the moveable items and integrates with the existing msg / model / update cycle.

**Comment by stuartleech** [comment]
![Social Messaging Example](https://github.com/cookiewolf/bi4c8d/assets/15141003/d1944f2c-cce4-4303-ae2a-74b2270dc816)
![Moveable Elements Image Gallery](https://github.com/cookiewolf/bi4c8d/assets/15141003/3be28f0a-3dc6-41ba-9019-d4fbf5349076)

**Comment by stuartleech** [comment]
Another site with similar functionality: https://sub.global/

**Comment by stuartleech** [comment]
<img width="726" alt="Screenshot 2024-07-15 at 10 21 25" src="https://github.com/user-attachments/assets/2a855e7c-5597-40f5-acdb-3c712e21c826">
