### ISSUE TITLE
Tests we should write

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#40]
## Plan
- [ ] Messages are ordered by date
- [ ] Message date only appears above the first message from that day
- [ ] Message viewCount displays by k (and future by mil ?)
- [ ] Content with section ID appears in correct section
- [ ] Sections can have top main text (with title) and bottom main texts (without titles)
- [ ] Chart stuff
