### ISSUE TITLE
Section 4 - Facial recognition images

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#8]
## Fields
- [ ] Image & mask image pairs

## Plan
- [ ] Add to CMS
- [ ] View with stoping animation

**Comment by katjam** [comment]
![image](https://github.com/cookiewolf/bi4c8d/assets/861172/1f338935-ece3-44d2-936d-ccda32f1885f)

**Comment by stuartleech** [comment]
I need to prepare images for this section and provide pngs
