### ISSUE TITLE
Section 5 - Add Face images --> Information

### ISSUE THREAD

**Issue by katjam** [cookiewolf/bi4c8d#9]
## Fields
- [ ] Face images
- [ ] Information about each
- [ ] Position ? Hardcoded to match final whitesquare image
- [ ] Explanation of how we got the content

## Plan
- [ ] Add to CMS
- [ ] fade in animation

**Comment by katjam** [comment]
![image](https://github.com/cookiewolf/bi4c8d/assets/861172/dd5c5a9c-3d5b-48e4-a6db-bef5bb0642f4)
